### ISSUE TITLE
Object index is skipping on elements

### ISSUE THREAD

**Issue by guidedways** [jornane/plist#1]
See line 338 in BinaryWriter

`if (!objectIndex.contains(obj)) {`

It's actually skipping on elements if there exists a similar named one already. For example, it's totally legit to have a NSDictionary have a key 'somekey' with value 'somekey'. This line will end up skipping it, not to mention the 'indexOf(o)' will return the incorrect index for the value of this dictionary. This is a serious bug.

**Comment by jornane** [comment]
Can you provide some example code? The following code works fine when I test it:

``` java
public static void main(String... args) throws PropertyListException, IOException {
    NSString foo = new NSString("somekey");
    HashMap<String,NSObject> map1 = new HashMap<String, NSObject>();
    HashMap<String,NSObject> map2 = new HashMap<String, NSObject>();
    map2.put("somekey", foo);
    map1.put("somekey", new NSDictionary(map2));

    NSDictionary dict = new NSDictionary(map1);

    BinaryWriter.write(dict, new File("test.plist"));
}
```

This generates the following file (which indeed contains the string `somekey` only once – it doesn't need to repeat it)

```
62 70 6C 69 73 74 30 30  D1 01 02 57 73 6F 6D 65 6B 65  bplist00-..Wsomeke
79 D1 01 01 08 0B 13 00  00 00 00 00 00 01 01 00 00 00  y-................
00 00 00 00 03 00 00 00  00 00 00 00 00 00 00 00 00 00  ..................
00 00 16                                                ...
```

Which can be converted to the following XML:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>somekey</key>
    <dict>
        <key>somekey</key>
        <string>somekey</string>
    </dict>
</dict>
</plist>
```

**Comment by guidedways** [comment]
Okay so it seems a small change I made was in NSString where 'equals' checks without case sensitivity, which means that the code above would fail if one of the keys had a different case, such as:

```
HashMap<String,NSObject> map1 = new HashMap<String, NSObject>();
HashMap<String,NSObject> map2 = new HashMap<String, NSObject>();
map2.put("somekey", new NSString("first one"));
map2.put("anotherkey", new NSString("Somekey"));
map1.put("somekey", new NSDictionary(map2));

NSDictionary dict = new NSDictionary(map1);
```

The value "Somekey" will get written as "somekey". I can't now remember why I had to rely on a case insensitive match, but I wrote a PLIST parse which needed for it do that since I was reading PLISTs from developers that wouldn't always use the correct case (yet the keys had to match and were unique).

**Comment by jornane** [comment]
It's always annoying when you have to work with inconsistent input. However, it's not a problem this library is intended to solve, and changing the equals method of a string to be case insensitive can have unintended side-effects. The original code does not exhibit this bug.
